import React from 'react'
import '../sass/globals.scss'
import Header from '@/components/Header'
import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
import WorkInProgress from '@/components/WorkInProgress'
import { barlowCondensed } from '@/resources/fonts'
config.autoAddCss = false

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html className={barlowCondensed.className}>
      <body>
        <WorkInProgress />
        <Header />
        {children}
      </body>
    </html>
  )
}

export default RootLayout
