import React from 'react'
import '../sass/globals.scss'
import Header from '@/components/Header'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html>
      <body>
        <Header />
        {children}
      </body>
    </html>
  )
}

export default RootLayout
